# Generated by Django 5.1.1 on 2024-10-17 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_alter_articles_cover'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articles',
            options={'verbose_name': 'Товар', 'verbose_name_plural': 'Товары'},
        ),
        migrations.RemoveField(
            model_name='articles',
            name='anons',
        ),
        migrations.RemoveField(
            model_name='articles',
            name='full_text',
        ),
        migrations.RemoveField(
            model_name='articles',
            name='title',
        ),
        migrations.AddField(
            model_name='articles',
            name='category',
            field=models.CharField(blank=True, max_length=70, verbose_name='Категория товара'),
        ),
        migrations.AddField(
            model_name='articles',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание товара'),
        ),
        migrations.AddField(
            model_name='articles',
            name='length',
            field=models.CharField(blank=True, max_length=270, verbose_name='Длина товара'),
        ),
        migrations.AddField(
            model_name='articles',
            name='name',
            field=models.CharField(blank=True, max_length=270, verbose_name='Название товара'),
        ),
        migrations.AddField(
            model_name='articles',
            name='price',
            field=models.CharField(blank=True, max_length=270, verbose_name='Цена товара'),
        ),
        migrations.AddField(
            model_name='articles',
            name='remains',
            field=models.CharField(blank=True, max_length=270, verbose_name='Остаток на складе'),
        ),
        migrations.AddField(
            model_name='articles',
            name='set',
            field=models.CharField(blank=True, max_length=270, verbose_name='Комплект товара'),
        ),
        migrations.AddField(
            model_name='articles',
            name='thickness',
            field=models.CharField(blank=True, max_length=270, verbose_name='Толщина товара'),
        ),
        migrations.AddField(
            model_name='articles',
            name='weight',
            field=models.CharField(blank=True, max_length=270, verbose_name='Вес товара'),
        ),
        migrations.AlterField(
            model_name='articles',
            name='cover',
            field=models.ImageField(blank=True, upload_to='images/post'),
        ),
        migrations.AlterField(
            model_name='articles',
            name='date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления'),
        ),
    ]
