# Generated by Django 5.1.1 on 2024-10-17 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0007_alter_articles_options_remove_articles_anons_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='category',
            field=models.CharField(blank=True, choices=[('nabor', 'Набор'), ('podstavka', 'Подставка'), ('dr', 'Другая')], max_length=70, verbose_name='Категория товара'),
        ),
    ]
