# Generated by Django 5.1.1 on 2024-11-17 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_articles_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='length',
            field=models.IntegerField(blank=True, max_length=270, verbose_name='Длина товара'),
        ),
        migrations.AlterField(
            model_name='articles',
            name='price',
            field=models.IntegerField(blank=True, max_length=270, verbose_name='Цена товара'),
        ),
        migrations.AlterField(
            model_name='articles',
            name='thickness',
            field=models.IntegerField(blank=True, max_length=270, verbose_name='Толщина товара'),
        ),
        migrations.AlterField(
            model_name='articles',
            name='weight',
            field=models.IntegerField(blank=True, max_length=270, verbose_name='Вес товара'),
        ),
    ]
