# Generated by Django 5.1.1 on 2024-11-18 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_articles_thickness'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='length',
            field=models.FloatField(blank=True, verbose_name='Длина товара'),
        ),
        migrations.AlterField(
            model_name='articles',
            name='weight',
            field=models.FloatField(blank=True, verbose_name='Вес товара'),
        ),
    ]
