# Generated by Django 5.1.1 on 2024-11-18 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_articles_length_alter_articles_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='price',
            field=models.IntegerField(blank=True, verbose_name='Цена товара'),
        ),
    ]
