# Generated by Django 5.1.1 on 2024-11-18 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_alter_articles_length'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='price',
            field=models.IntegerField(verbose_name='Цена товара'),
        ),
        migrations.AlterField(
            model_name='articles',
            name='weight',
            field=models.FloatField(blank=True, null=True, verbose_name='Вес товара'),
        ),
    ]
