# Generated by Django 5.1.1 on 2024-11-18 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_articles_length_alter_articles_thickness_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='thickness',
            field=models.FloatField(blank=True, null=True, verbose_name='Толщина товара'),
        ),
    ]
