# Generated by Django 5.1.1 on 2024-11-18 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_alter_articles_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='length',
            field=models.FloatField(blank=True, null=True, verbose_name='Длина товара'),
        ),
    ]
